### ISSUE TITLE
Submit a Cloud Definition ~ Network Security Group

### ISSUE THREAD

**Issue by ArtistYay** [learntocloud/cloud-dictionary#10]
- Word: Network Security Group
- Content: A network security group is a set of rules that allows or denies who (based on IP address) and what (based on protocol/port) network traffic can come in and out of a VNET.
- Author Name: Athina (Artist) Thomas
- Author Link]: https://linktr.ee/artistyay?utm_source=linktree_profile_share&ltsid=eb1e0777-ebd7-413f-9300-a7222f886d9b
- Learn More: (https://learn.microsoft.com/en-us/azure/virtual-network/network-security-group-how-it-works)
- Category: network, security
- Abbreviation: NSG

**Comment by madebygps** [comment]
Network security has already been submitted, thank you :) please check https://zealous-flower-0f27b070f.2.azurestaticapps.net/ for submitted words.
