### ISSUE TITLE
Submit a Cloud Definition - auto scaling

### ISSUE THREAD

**Issue by rishabkumar7** [learntocloud/cloud-dictionary#11]
- Word [REQUIRED]: **auto-scaling**
- Content [REQUIRED]: auto-scaling refers to a cloud infrastructure's ability to automatically adjust the capacity of its resources based on demand. This is acheived through the use of rules and monitoring systems that continuously analyse the performance of the cloud infrastructure and dynamically adjust the number of resources (such as virtual machines, storage, and network bandwidth) to ensure that the infrastructure is optimised for both performance and cost.
- Author Name [REQUIRED]: Rishab Kumar
- Author Link [REQUIRED]: https://twitter.com/rishabk7
- Learn More URL [REQUIRED]: https://en.wikipedia.org/wiki/Autoscaling
- Category [REQUIRED, select one]: compute
- Abbreviation [OPTIONAL]: If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

**Comment by madebygps** [comment]
Added, thank you!
