### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by ifeanyiro9** [learntocloud/cloud-dictionary#114]
Do NOT copy/paste a definition from somewhere else. Read about the word you want to define and come up with your own definition. Copy/Paste submissions will be closed and not added.

Fill out the JSON with your submission:

```json
    {
    "word": "GitHub",
    "content": "GitHub is a user-friendly web-based platform that uses the popular version control system Git to store, manage, track changes, collaborate with others and deploy software projects.",
    "learn_more_URL":"https://www.simplilearn.com/tutorials/git-tutorial/what-is-github",
    "tag":"developer tool",
    "abbreviation": "",
    "author_name":"Ifeanyi Otuonye",
    "author_link": "https://www.linkedin.com/in/ifeanyi-otuonye/"
    }
```
Fill out the JSON below with the following.

### Word (REQUIRED)

The word you are defining. Check [this URL](https://zealous-flower-0f27b070f.2.azurestaticapps.net/) for all words we currently have.

#### Content (REQUIRED)

The definition. No more than 3 sentences.

### learn more URL (REQUIRED)

Website where people can visit to learn more about the word.

### tag (REQUIRED and select one)

Tech category the word fits in. Options:

- compute
- security
- service
- general
- analytics
- developer tool
- web
- networking
- database
- storage
- devops
- ai/ml
- identity
- iot
- monitoring
- cost management
- disaster recovery

### abbreviation (OPTIONAL)

If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

### author name (REQUIRED)

Your name.

### author link (REQUIRED)

The URL you want your name to link to.

**Comment by ifeanyiro9** [comment]
Jeez, my system glitched before I could complete this properly.

**Comment by ifeanyiro9** [comment]
Fixed.

**Comment by Acekhing** [comment]
Hi there! 
Is the definition added from the frontend Blazor app?

**Comment by ifeanyiro9** [comment]
Hi,
I'm not sure I understand well the question. Do you mean if got the definition from that app? Or if I used that app to create the definition, or If I used the app to submit the definition?

**Comment by madebygps** [comment]
hi @ifeanyiro9 I've added your definition :) 
@Acekhing Please checkout https://zealous-flower-0f27b070f.2.azurestaticapps.net/ for all submitted definitions.

**Comment by Acekhing** [comment]
Yeah. was asking if you use the app to submit the question. Also is it possible to submit definitions since the issue has already been assigned?

**Comment by Acekhing** [comment]
Yeah. was asking if you use the app to submit the question. Also is it possible to submit definitions since the issue has already been assigned?

**Comment by madebygps** [comment]
@Acekhing Please open a new issue to submit a definition.
