### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by Ankit6989** [learntocloud/cloud-dictionary#116]
Do NOT copy/paste a definition from somewhere else. Read about the word you want to define and come up with your own definition. Copy/Paste submissions will be closed and not added.

Fill out the JSON with your submission:

```json
    {
    "word": "Super Key",
    "content": "A Super Key is a group of single or multiple keys which identifies rows in a table. A Super Key may have additional attributes that are not needed for unique identification.",
    "learn_more_URL":"https://www.scaler.com/topics/super-key-in-dbms/",
    "tag":"database",
    "abbreviation": "",
    "author_name":"Ankit",
    "author_link": "https://github.com/Ankit6989"
    }
```
Fill out the JSON below with the following.

### Word (REQUIRED)

The word you are defining. Check [this URL](https://zealous-flower-0f27b070f.2.azurestaticapps.net/) for all words we currently have.

#### Content (REQUIRED)

The definition. No more than 3 sentences.

### learn more URL (REQUIRED)

Website where people can visit to learn more about the word.

### tag (REQUIRED and select one)

Tech category the word fits in. Options:

- compute
- security
- service
- general
- analytics
- developer tool
- web
- networking
- database
- storage
- devops
- ai/ml
- identity
- iot
- monitoring
- cost management
- disaster recovery

### abbreviation (OPTIONAL)

If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

### author name (REQUIRED)

Your name.

### author link (REQUIRED)

The URL you want your name to link to.

**Comment by madebygps** [comment]
Please provide a value for `learn_more_url"

**Comment by Ankit6989** [comment]
Hey I have updated the url

**Comment by madebygps** [comment]
Added, thank you for your submission :)
