### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by jamchi16** [learntocloud/cloud-dictionary#117]
Do NOT copy/paste a definition from somewhere else. Read about the word you want to define and come up with your own definition. Copy/Paste submissions will be closed and not added.

Fill out the JSON with your submission:

```json
    {
    "word": "Kubernetes",
    "content": "An open source container management platform. Used for the automation, scheduling, scaling, and deployment of containers and applications.",
    "learn_more_URL":"https://azure.microsoft.com/en-us/resources/cloud-computing-dictionary/what-is-kubernetes/",
    "tag":"devops",
    "abbreviation": "",
    "author_name":"James",
    "author_link": "https://github.com/jamchi16?tab=repositories"
    }
```
Fill out the JSON below with the following.

### Word (REQUIRED)

The word you are defining. Check [this URL](https://zealous-flower-0f27b070f.2.azurestaticapps.net/) for all words we currently have.

#### Content (REQUIRED)

The definition. No more than 3 sentences.

### learn more URL (REQUIRED)

Website where people can visit to learn more about the word.

### tag (REQUIRED and select one)

Tech category the word fits in. Options:

- compute
- security
- service
- general
- analytics
- developer tool
- web
- networking
- database
- storage
- devops
- ai/ml
- identity
- iot
- monitoring
- cost management
- disaster recovery

### abbreviation (OPTIONAL)

If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

### author name (REQUIRED)

Your name.

### author link (REQUIRED)

The URL you want your name to link to.

**Comment by madebygps** [comment]
this word has already been submitted, please review the dictionary site before submitting a word. thank you.
