### ISSUE TITLE
Submit a Cloud Definition ~ Scalability

### ISSUE THREAD

**Issue by ArtistYay** [learntocloud/cloud-dictionary#12]
- Word: Scalability
- Content: One of the core design principles or best practice needed in a highly available environment. You can scale up (increase the VM size) or scale out (increase the number of VMs) when a workload of a system is overloaded. For example, a shoe release on a site increases traffic for the web server, one way to mitigate this is using an auto scale to scale out more VMs or web servers and have your load balancer distribute the traffic evenly.
- Author Name: Athina (Artist) Thomas
- Author Link: https://linktr.ee/artistyay?fbclid=PAAaYkcfWyjCkgqM-JdaL03_xhx3bZTl7wT5a2wQpgWAmAqmCPG6nqr8mk_70
- Learn More URL: (https://www.geeksforgeeks.org/scalability-and-elasticity-in-cloud-computing/)
- Category: general, compute
- Abbreviation: N/A

**Comment by madebygps** [comment]
Scalability has already been submitted, thank you :) please check https://zealous-flower-0f27b070f.2.azurestaticapps.net/ for submitted words.
