### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by Dclark2434** [learntocloud/cloud-dictionary#126]
Do NOT copy/paste a definition from somewhere else. Read about the word you want to define and come up with your own definition. Copy/Paste submissions will be closed and not added.

Fill out the JSON with your submission:

```json
    {
    "word": "Cloudbursting",
    "content": "Utilizing the public cloud for overflow of traffic when internal or private cloud resources have reached peak capacity. Not to be confused with Cloudbusting, a great song.",
    "learn_more_URL":"https://www.gartner.com/en/information-technology/glossary/cloudbursting",
    "tag":"general",
    "abbreviation": "",
    "author_name":"Dustin Clark",
    "author_link": "https://www.github.com/dclark2434"
    }
```
Fill out the JSON below with the following.

### Word (REQUIRED)

The word you are defining. Check [this URL](https://definethecloud.guide) for all words we currently have.

#### Content (REQUIRED)

The definition. No more than 3 sentences.

### learn more URL (REQUIRED)

Website where people can visit to learn more about the word.

### tag (REQUIRED and select one)

Tech category the word fits in. Options:

- compute
- security
- service
- general
- analytics
- developer tool
- web
- networking
- database
- storage
- devops
- ai/ml
- identity
- iot
- monitoring
- cost management
- disaster recovery

### abbreviation (OPTIONAL)

If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

### author name (REQUIRED)

Your name.

### author link (REQUIRED)

The URL you want your name to link to.

**Comment by Project-Xenith** [comment]
Is there a list of words which have been covered till now?

**Comment by madebygps** [comment]
@Dclark2434  this word has already been submitted.

**Comment by madebygps** [comment]
@Project-Xenith yes, read the instructions:

Word (REQUIRED)
The word you are defining. Check [this URL](https://definethecloud.guide/) for all words we currently have.
