### ISSUE TITLE
Submit a Cloud Definition ~ version control

### ISSUE THREAD

**Issue by ArtistYay** [learntocloud/cloud-dictionary#13]
- Word: Version control
- Content: A type of system that keeps track of changes to code in one or more files. For example, let's say you work in a team, and you all have to make changes to the code in the main branch of your repository, you can keep track of one another's progress and make sure you're not conflicting with each other's work. A popular version control system is Git.
- Author Name: Athina (Artist) Thomas
- Author Link: https://linktr.ee/artistyay?fbclid=PAAaYkcfWyjCkgqM-JdaL03_xhx3bZTl7wT5a2wQpgWAmAqmCPG6nqr8mk_70
- Learn More URL: https://www.atlassian.com/git/tutorials/what-is-version-control
- Category: developer, devops
- Abbreviation: VCS

**Comment by madebygps** [comment]
Version control has already been submitted, thank you :) please check https://zealous-flower-0f27b070f.2.azurestaticapps.net/ for submitted words.
