### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by Antoniorios17** [learntocloud/cloud-dictionary#133]
Do NOT copy/paste a definition from somewhere else. Read about the word you want to define and come up with your own definition. Copy/Paste submissions will be closed and not added.

Fill out the JSON with your submission:

```json
    {
    "word": "python",
    "content": "Python is an open source programming language, interpreted and object-oriented. Python is very flexible and has many libraries for a variety of use cases. Python is one of the most popular programming languages today ",
    "learn_more_URL":"https://www.python.org/about/gettingstarted/",
    "tag":"ai/ml",
    "abbreviation": "py",
    "author_name":"Antonio Rios",
    "author_link": "https://www.linkedin.com/in/antoniorios17/"
    }
```
Fill out the JSON below with the following.

### Word (REQUIRED)

The word you are defining. Check [this URL](https://definethecloud.guide) for all words we currently have.

#### Content (REQUIRED)

The definition. No more than 3 sentences.

### learn more URL (REQUIRED)

Website where people can visit to learn more about the word.

### tag (REQUIRED and select one)

Tech category the word fits in. Options:

- compute
- security
- service
- general
- analytics
- developer tool
- web
- networking
- database
- storage
- devops
- ai/ml
- identity
- iot
- monitoring
- cost management
- disaster recovery

### abbreviation (OPTIONAL)

If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

### author name (REQUIRED)

Your name.

### author link (REQUIRED)

The URL you want your name to link to.

**Comment by madebygps** [comment]
Did some rewording, thank you :) https://definethecloud.guide/definitions/python
