### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by caginberke** [learntocloud/cloud-dictionary#134]
Do NOT copy/paste a definition from somewhere else. Read about the word you want to define and come up with your own definition. Copy/Paste submissions will be closed and not added.

Fill out the JSON with your submission:

```json
    {
    "word": "Canary Deployment",
    "content": "The idea behind this approach is to release a new version of software or application to a small group of users first, usually a certain percentage of the overall user base, before making it available to everyone at once.",
    "learn_more_URL":"https://cloud.google.com/deploy/docs/deployment-strategies/canary#:~:text=A%20canary%20deployment%20is%20a,users%20before%20rolling%20out%20fully.",
    "tag":"devops",
    "abbreviation": "",
    "author_name":"Çağın",
    "author_link": "https://github.com/caginberke"
    }
```
Fill out the JSON below with the following.

### Word (REQUIRED)

The word you are defining. Check [this URL](https://definethecloud.guide) for all words we currently have.

#### Content (REQUIRED)

The definition. No more than 3 sentences.

### learn more URL (REQUIRED)

Website where people can visit to learn more about the word.

### tag (REQUIRED and select one)

Tech category the word fits in. Options:

- compute
- security
- service
- general
- analytics
- developer tool
- web
- networking
- database
- storage
- devops
- ai/ml
- identity
- iot
- monitoring
- cost management
- disaster recovery

### abbreviation (OPTIONAL)

If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

### author name (REQUIRED)

Your name.

### author link (REQUIRED)

The URL you want your name to link to.

**Comment by madebygps** [comment]
We've got https://definethecloud.guide/canary-release already, thank you.
