### ISSUE TITLE
Submit a Cloud Definition - Transit Gateway

### ISSUE THREAD

**Issue by josevill** [learntocloud/cloud-dictionary#14]
- Word [REQUIRED]: Transit Gateway
- Content [REQUIRED]: Solution that will give you a central point or hub to interconnect multiple networks, be it VPNs or Virtual networks as VPC in a multi account environment. This will empower you to manage routing, connectivity and provide you with certain monitoring capabilities on your enterprise networking environment, be it a fully cloud environment or a hybrid one, you will be able to handle the connectivity in between your networks with this solution.
- Author Name [REQUIRED]: Jose Manuel Viloria
- Author Link [REQUIRED]: https://www.linkedin.com/in/kbono/
- Learn More URL [REQUIRED]: https://docs.aws.amazon.com/vpc/latest/tgw/what-is-transit-gateway.html
- Category [REQUIRED, select one]: networking
- Abbreviation [OPTIONAL]: tgw

**Comment by madebygps** [comment]
Thank you, added!
