### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by tbsharkey** [learntocloud/cloud-dictionary#140]
Do NOT copy/paste a definition from somewhere else. Read about the word you want to define and come up with your own definition. Copy/Paste submissions will be closed and not added.

Fill out the JSON with your submission:

```json
    {
    "word": "Amazon EBS",
    "content": "Elastic Block Store (EBS) is Amazon Web Services' block-level storage solution designed for EC2 instances, offering persistent and scalable storage volumes. Similar to a laptop's hard drive, EBS enables EC2 instances to store data independently, and volumes can be created with specified sizes and performance characteristics to meet diverse application needs. EBS provides the flexibility to attach and detach volumes to EC2 instances seamlessly, enhancing storage management and data durability.",
    "learn_more_URL":"https://aws.amazon.com/ebs/",
    "tag":"compute",
    "abbreviation": "EBS",
    "author_name":"Tom Sharkey",
    "author_link": "https://www.tomsharkey.com"
    }
```
Fill out the JSON below with the following.

### Word (REQUIRED)

The word you are defining. Check [this URL](https://definethecloud.guide) for all words we currently have.

#### Content (REQUIRED)

The definition. No more than 3 sentences.

### learn more URL (REQUIRED)

Website where people can visit to learn more about the word.

### tag (REQUIRED and select one)

Tech category the word fits in. Options:

- compute
- security
- service
- general
- analytics
- developer tool
- web
- networking
- database
- storage
- devops
- ai/ml
- identity
- iot
- monitoring
- cost management
- disaster recovery

### abbreviation (OPTIONAL)

If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

### author name (REQUIRED)

Your name.

### author link (REQUIRED)

The URL you want your name to link to.

**Comment by madebygps** [comment]
Added, https://definethecloud.guide/amazon-ebs thank you
