### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by Akshaykumar05** [learntocloud/cloud-dictionary#16]
- Word: Cloud
- Content: "The cloud" refers to servers that are accessed over the Internet, and the software and databases that run on those servers. Cloud servers are located in data centers all over the world.
- Author Name: Akshay Kumar
- Author Link: https://twitter.com/akshayktwt
- Learn More URL [REQUIRED]: https://www.cloudflare.com/en-gb/learning/cloud/what-is-the-cloud/
- Category: DevOps

**Comment by madebygps** [comment]
Nice one, I've added it, thank you for your contribution.

**Comment by Akshaykumar05** [comment]
Thank you GPS for the opportunity! It's a pleasure to contribute to this
LTC project.
