### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by Ayomide05** [learntocloud/cloud-dictionary#161]
Do NOT copy/paste a definition from somewhere else. Read about the word you want to define and come up with your own definition. Copy/Paste submissions will be closed and not added.

Fill out the JSON with your submission:

```json
    {
    "word": "Cloud",
    "content": "Cloud is a term used to describe a broad collection of multiple remote servers around the globe/universe each with a distinctive function linked together and are meant to operate as a single ecosystem ",
    "learn_more_URL":"https://azure.microsoft.com/en-us/resources/cloud-computing-dictionary/what-is-the-cloud#:~:text=The%20definition%20for%20the%20cloud,operate%20as%20a%20single%20ecosystem.",
    "tag":"general",
    "abbreviation": "",
    "author_name":"Gabriel Justina",
    "author_link": "github.com/Ayomide05"
    }
```
Fill out the JSON below with the following.

### Word (REQUIRED)

The word you are defining. Check [this URL](https://definethecloud.guide) for all words we currently have.

#### Content (REQUIRED)

The definition. No more than 3 sentences.

### learn more URL (REQUIRED)

Website where people can visit to learn more about the word.

### tag (REQUIRED and select one)

Tech category the word fits in. Options:

- compute
- security
- service
- general
- analytics
- developer tool
- web
- networking
- database
- storage
- devops
- ai/ml
- identity
- iot
- monitoring
- cost management
- disaster recovery

### abbreviation (OPTIONAL)

If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

### author name (REQUIRED)

Your name.

### author link (REQUIRED)

The URL you want your name to link to.

**Comment by madebygps** [comment]
Hello, this already exists https://definethecloud.guide/cloud, please open an issue with a deifnition that doesn't already exist in the database, please check definethecloud.guide beforehand.
