### ISSUE TITLE
Submit a Cloud Definition ~ Virtual Network

### ISSUE THREAD

**Issue by ArtistYay** [learntocloud/cloud-dictionary#18]
- Word: Virtual Network
- Content: A virtual network is a private space in Azure where you can add certain resources to communicate with each other without the use of the internet. You can compare it to a VLAN.
- Author Name: Athina (Artist) Thomas
- Author Link: https://linktr.ee/artistyay?fbclid=PAAaYkcfWyjCkgqM-JdaL03_xhx3bZTl7wT5a2wQpgWAmAqmCPG6nqr8mk_70
- Learn More URL: https://learn.microsoft.com/en-us/azure/virtual-network/virtual-networks-overview
- Category: networking
- Abbreviation [OPTIONAL]: VNET

**Comment by madebygps** [comment]
Nice one, I've added it, thank you!
