### ISSUE TITLE
Submit a Cloud Definition ~ Security Group

### ISSUE THREAD

**Issue by ArtistYay** [learntocloud/cloud-dictionary#19]
- Word [REQUIRED]: Security Group
- Content [REQUIRED]: A network security group is a set of rules that allows or denies who (based on IP address) and what (based on protocol/port) network traffic can come in and out of a VPC.
- Author Name [REQUIRED]: Athina (Artist) Thomas
- Author Link [REQUIRED]: https://linktr.ee/artistyay?utm_source=linktree_profile_share&ltsid=eb1e0777-ebd7-413f-9300-a7222f886d9b
- Learn More URL [REQUIRED]: https://docs.aws.amazon.com/vpc/latest/userguide/VPC_SecurityGroups.html
- Category [REQUIRED, select one]: network, security
- Abbreviation [OPTIONAL]: If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

**Comment by madebygps** [comment]
We've got this one added already :) thanks!
