### ISSUE TITLE
Submit a Cloud Definition ~ Cloud Security

### ISSUE THREAD

**Issue by ArtistYay** [learntocloud/cloud-dictionary#20]
- Word [REQUIRED]: Cloud Security
- Content [REQUIRED]: Cloud security is a practice with the collection of procedures with the use of cloud-based tools to protect data, users, and services in your environment in the cloud.
- Author Name [REQUIRED]: Athina (Artist) Thomas
- Author Link [REQUIRED]: https://linktr.ee/artistyay?fbclid=PAAaYkcfWyjCkgqM-JdaL03_xhx3bZTl7wT5a2wQpgWAmAqmCPG6nqr8mk_70
- Learn More URL [REQUIRED]: https://www.ibm.com/topics/cloud-security
- Category [REQUIRED, select one]: security
- Abbreviation [OPTIONAL]: If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

**Comment by madebygps** [comment]
Nice one, I've added it, thank you!
