### ISSUE TITLE
Submit a Cloud Definition - Vertical Scaling

### ISSUE THREAD

**Issue by jbright-dev** [learntocloud/cloud-dictionary#21]
- Word [REQUIRED]: Vertical Scaling
- Content [REQUIRED]: The ability to increase or decrease processing power by adding or removing additional CPUs or RAM; For instance: If you need extra ram you can scale upwards by adding CPUs or RAM. When you no longer require the same processing power you can scale down by removing those same CPUs or RAM. 
- Author Name [REQUIRED]: Jason Bright
- Author Link [REQUIRED]: https://www.linkedin.com/in/jason-bright-dev/
- Learn More URL [REQUIRED]: https://learn.microsoft.com/en-us/training/modules/describe-benefits-use-cloud-services/2-high-availability-scalability-cloud
- Category [REQUIRED, select one]: Compute

**Comment by madebygps** [comment]
Nice one, I've added it, thank you!
