### ISSUE TITLE
Submit a Cloud Definition - Horizontal Scaling

### ISSUE THREAD

**Issue by jbright-dev** [learntocloud/cloud-dictionary#22]
- Word [REQUIRED]: Horizontal Scaling
- Content [REQUIRED]: The ability to increase or decrease the number of virtual machines or containers. For example; you require multiple Virtual Machines to process payments so you scale outwardly. Upon completion, you scale inwardly by reducing the number of virtual machines you previously instantiated. 
- Author Name [REQUIRED]: Jason Bright
- Author Link [REQUIRED]: https://www.linkedin.com/in/jason-bright-dev/
- Learn More URL [REQUIRED]: https://learn.microsoft.com/en-us/training/modules/describe-benefits-use-cloud-services/2-high-availability-scalability-cloud
- Category [REQUIRED, select one]: Compute

**Comment by madebygps** [comment]
Nice one, I've added it, thank you!
