### ISSUE TITLE
Submit a Cloud Definition - Instantiate 

### ISSUE THREAD

**Issue by jbright-dev** [learntocloud/cloud-dictionary#23]
- word [REQUIRED]: Instantiate (verb)
- content [REQUIRED]: ); the creation of an object; for example, you instantiate three virtual machine resources. These virtual machines can also be called three virtual machine "instances".
- Author Name [REQUIRED]: Jason Bright
- Author Link [REQUIRED]: https://www.linkedin.com/in/jason-bright-dev/
- Learn More URL [REQUIRED]: https://www.techopedia.com/definition/26857/instantiate
- Category [REQUIRED, select one]: Compute

**Comment by madebygps** [comment]
Added, thank you!
