### ISSUE TITLE
Submit a Cloud Definition - Capital Expenditure (CapEx)

### ISSUE THREAD

**Issue by jbright-dev** [learntocloud/cloud-dictionary#24]
- word [REQUIRED]: Capital Expenditure (CapEx)
- content [REQUIRED]: The expense incurred when acquiring an asset that generates benefits for a business over a long period. For example, the $50,000 cost incurred when purchasing servers is a capital expense due to the purchase price and the mandated useful life of "7" years (as indicated by the United States Internal Revenue Service). 
- Author Name [REQUIRED]: Jason Bright
- Author Link [REQUIRED]: https://www.linkedin.com/in/jason-bright-dev/
- Learn More URL [REQUIRED]: https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/business-outcomes/fiscal-outcomes; https://www.irs.gov/irm/part1/irm_01-035-006#idm140486824982768
- Category [REQUIRED, select one]: Cloud Costs

**Comment by madebygps** [comment]
fantastic one! thank you J
