### ISSUE TITLE
Submit a Cloud Definition - Operational Expenditures (OpEx)

### ISSUE THREAD

**Issue by jbright-dev** [learntocloud/cloud-dictionary#25]
- word [REQUIRED]: Operational Expenditures (OpEx)
- content [REQUIRED]: The ongoing costs incurred by a business during its day-to-day activities. For example, a company spends $4,167 for cloud services each month during a twelve-month period, resulting in a yearly operational expense of $50,004.
- Author Name [REQUIRED]: Jason Bright
- Author Link [REQUIRED]: https://www.linkedin.com/in/jason-bright-dev/
- Learn More URL [REQUIRED]:[1] https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/strategy/business-outcomes/fiscal-outcomes
- Category [REQUIRED, select one]: Cloud Costs

**Comment by madebygps** [comment]
fantastic one! thank you J
