### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by alexkourtis98** [learntocloud/cloud-dictionary#26]
- word [REQUIRED]: High availability
- content [REQUIRED]: Is one of the benefits of the cloud that help maintain availability due to network outages, app failure, power outages and more
- learn more URL [REQUIRED]: https://www.techtarget.com/searchdatacenter/definition/high-availability.
- tag [REQUIRED, select one]: service
- abbreviation [OPTIONAL]: HA
- author name [REQUIRED]: Alexandros Kourtis
- author link [REQUIRED]: https://github.com/alexkourtis98

**Comment by madebygps** [comment]
all good :)
