### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by alexkourtis98** [learntocloud/cloud-dictionary#27]
- word [REQUIRED]: Zero Trust
- content [REQUIRED]: Zero Trust is a strategic approach to cybersecurity that secures an organization by eliminating implicit trust and continuously validating every stage of a digital interaction.
- learn more URL [REQUIRED]: https://en.wikipedia.org/wiki/Zero_trust_security_model
- tag [REQUIRED, select one]: security
- abbreviation [OPTIONAL]: ZTA
- author name [REQUIRED]: Alexandros Kourtis
- author link [REQUIRED]: https://github.com/alexkourtis98

**Comment by madebygps** [comment]
fantastic one! thank you Alexandros
