### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by lakshmanshankarc** [learntocloud/cloud-dictionary#28]
- word: LVM
- content [REQUIRED]: Linux storage virtualization
- learn more URL [REQUIRED
]: https://en.m.wikipedia.org/wiki/Logical_Volume_Manager_(Linux)
- tag : Storage
- abbreviation : Logic Volume Manager 
- author name [REQUIRED]: Lakshman
- author link [REQUIRED]: https://GitHub.com/Lakshmanshankar

**Comment by madebygps** [comment]
Hello, you're missing the definition of the concept, please provide that :) 
{
  "word": "Linux storage virtualization",
  "content": "",
  "learn_more_url": "https://en.m.wikipedia.org/wiki/Logical_Volume_Manager_(Linux)",
  "tag": "storage",
  "abbreviation": "LVM",
  "author_name": "Lakshman",
  "author_link": "https://github.com/Lakshmanshankar"
}

**Comment by lakshmanshankarc** [comment]
{
"word": "Linux storage virtualization",
"content": "lvm is a tool for managing volumes in Linux Operating system. It helps us to add remove volumes to the operating system",
"learn_more_url": "https://en.m.wikipedia.org/wiki/Logical_Volume_Manager_(Linux)",
"tag": "storage",
"abbreviation": "LVM",
"author_name": "Lakshman",
"author_link": "https://github.com/Lakshmanshankar"
}

**Comment by madebygps** [comment]
Added, thank you :)
