### ISSUE TITLE
Submit a Cloud Definition - Service Mesh

### ISSUE THREAD

**Issue by perplexedyawdie** [learntocloud/cloud-dictionary#29]
- word [REQUIRED]: Service Mesh
- content [REQUIRED]: This is an infrastructure layer that handles inter-service communications. Any extra logic that controlled for e.g: capturing latency metrics or splitting traffic among services can be extracted into the service mesh instead.
- learn more URL [REQUIRED]: [What is a service mesh](https://www.redhat.com/en/topics/microservices/what-is-a-service-mesh)
- tag [REQUIRED, select one]: devops
- author name [REQUIRED]: Javel Rowe
- author link [REQUIRED]: [My Github 🐙](https://github.com/perplexedyawdie)

**Comment by madebygps** [comment]
good one, thank you :)
