### ISSUE TITLE
-Three-Tier Architecture

### ISSUE THREAD

**Issue by josephalan42** [learntocloud/cloud-dictionary#31]
- word [REQUIRED]:Three-Tier Architecture
- content [REQUIRED]: Three-tier architecture, which separates applications into three logical and physical computing tiers, is the predominant software architecture for traditional client-server applications.
- learn more URL [REQUIRED]: https://www.ibm.com/in-en/cloud/learn/three-tier-architecture
- tag [REQUIRED, select one]: Tech category the word fits in. Options: system design, cloud , architecture , three tier web application
- abbreviation [OPTIONAL]: If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.
- author name [REQUIRED]: Joseph Alan J
- author link [REQUIRED]: josephalan.online

**Comment by madebygps** [comment]
Added, thank you for your contribution.
