### ISSUE TITLE
Wrong definition displayed for the term

### ISSUE THREAD

**Issue by rghdrizzle** [learntocloud/cloud-dictionary#32]
The issue here is that , the definition for docker is being displayed for the term vendor lockin .
![image](https://user-images.githubusercontent.com/92255903/218292290-31863bb6-2fe4-4af8-88fa-355e575b1972.png)

**Comment by madebygps** [comment]
<img width="1512" alt="Screenshot 2023-02-11 at 11 04 38 PM" src="https://user-images.githubusercontent.com/6733686/218292440-f5f6ea18-9668-4357-a02f-3daea6a70184.png">

Thank you, just resolved that :)
