### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by alexcruzdev** [learntocloud/cloud-dictionary#33]
- word: Hypervisor
- content: It is a software that allows creating of multiple virtual machines in one hardware.
- learn more URL: [learn more](https://www.vmware.com/topics/glossary/content/hypervisor.html#:~:text=A%20hypervisor%2C%20also%20known%20as,such%20as%20memory%20and%20processing.)
- tag: virtualization
- abbreviation: VMM
- author name: Alex Cruz
- author link: [Twitter](https://twitter.com/alexcruzdev)

**Comment by madebygps** [comment]
Added! thank you for the contribution :)
