### ISSUE TITLE
Distributed System

### ISSUE THREAD

**Issue by ricardogomes** [learntocloud/cloud-dictionary#34]
{
  "word": "Distributed System",
  "content": "A set of independent networked components, orchestrated to behave as one system, that cooperate in order to achieve one or more objectives.",
  "learn_more_URL":"https://www.confluent.io/learn/distributed-systems/",
  "tag":"general",
  "abbreviation": "",
  "author_name":"Ricardo Gomes",
  "author_link": "https://ricardogomes.me"
}

**Comment by madebygps** [comment]
Added! thank you for the contribution :)
