### ISSUE TITLE
Public Key Infrastructure

### ISSUE THREAD

**Issue by ricardogomes** [learntocloud/cloud-dictionary#35]
{
  "word": "Public Key Infrastructure",
  "content": "Set of infractructure components and interfaces, that uses Public Key Cryptography to enable the usage of Digital Certificates. It can be set up in multiple ways but the most common is to have a Certificate Authority that is responsible for issuing and maintaining a list of certificates.",
  "learn_more_URL":"https://www.enisa.europa.eu/topics/incident-response/glossary/public-key-infrastructure-pki",
  "tag":"security",
  "abbreviation": "PKI",
  "author_name":"Ricardo Gomes",
  "author_link": "https://ricardogomes.me"
}

**Comment by madebygps** [comment]
Added and thank you for the contribution :)
