### ISSUE TITLE
Submit of a Cloud Definition - Internet of Things

### ISSUE THREAD

**Issue by jasjisdo** [learntocloud/cloud-dictionary#36]
Dear GPS,

Herewith I would like to submit, the definition for the term **Internet of Things (IoT)**. I have deposited my used sources in my [Wiki entry](https://github.com/jasjisdo/jasjisdo/wiki/Internet-of-Things-(IoT)). For this purpose, I have created a consolidated version of the definition.

Unfortunately, there are very many definitions of IoT. Therefore, I have chosen here a definition that focuses more on the use of cloud services.

Please find the needed json object below.

I hope this definition meets the desired quality requirements.
 
Best,

[Jaschar Jisreel Domann](https://github.com/jasjisdo)

---

```json
{
  "word": "Internet of Things",
  "content": "The Internet of Things (IoT) is a network of Internet-connected or other (e.g. Bluetooth LE, Z-Wave, Zigbee) network-connected devices, cyber physical systems or technology enhanced ('smart') everyday objects that transmit embedded sensor data to the cloud for central processing. Once the data is collected, it can be analyzed to provide meaningful, actionable insights. Cloud providers offer services such as AWS IoT Core, Azure IoT, Google Cloud IoT Core, which enable the secure central collection of sensor data via IoT-gateways.",
  "learn_more_URL":"https://github.com/jasjisdo/jasjisdo/wiki/Internet-of-Things-(IoT)",
  "tag":"iot, sensors, data, gateway, networking, web, analytics",
  "abbreviation": "IoT",
  "author_name":"Jaschar Jisreel Domann",
  "author_link": "https://github.com/jasjisdo"
}
```

**Comment by madebygps** [comment]
Added! thank you for the contribution :)
