### ISSUE TITLE
Submit a Cloud Definition - Firewall

### ISSUE THREAD

**Issue by Harshith-Shetty** [learntocloud/cloud-dictionary#38]
{
  "word": "Firewall",
  "content": "A firewall is a security system that monitors and controls incoming and outgoing network traffic based on predetermined security rules. It acts as a barrier between a private internal network and the public Internet, or between trusted and untrusted networks. Firewalls are designed to protect against unauthorized access, hacking attempts, malware, and other security threats by examining incoming and outgoing traffic and determining whether to allow or block specific traffic based on predefined rules.",
  "learn_more_URL":"https://www.cisco.com/c/en_in/products/security/firewalls/what-is-a-firewall.html",
  "tag":"security",
  "author_name":"Harshith Shetty",
  "author_link": "https://github.com/Harshith-Shetty"
}

**Comment by madebygps** [comment]
Added, thank you :)
