### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by Darthstevo** [learntocloud/cloud-dictionary#39]
Fill out the JSON below with the following.

- word [REQUIRED]: The word you are defining. Check [this URL](https://zealous-flower-0f27b070f.2.azurestaticapps.net/) for all words we currently have.
- content [REQUIRED]: The definition. No more than 3 sentences.
- learn more URL [REQUIRED]: Page where people can visit to learn more about the word.
- tag [REQUIRED, select one]: Tech category the word fits in. Options: compute, security, service, general, analytics, developer tools, web, networking, database, storage, devops, ai/ml, identiy, iot, monitoring.
- abbreviation [OPTIONAL]: If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.
- author name [REQUIRED]: Your name.
- author link [REQUIRED]: The URL you want your name to link to.

{
  "word": "Automation",
  "content": "The process of replacing a manual step with one that happens automatically",
  "learn_more_URL":https://www.computerhope.com/jargon/a/automati.htm"",
  "tag":devops"",
  "abbreviation": "",
  "author_name":"SP",
  "author_link":https://thebasictek.com/ ""
}

**Comment by madebygps** [comment]
Added, thank you :)
