### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by folusomaine** [learntocloud/cloud-dictionary#40]
Fill out the JSON below with the following.

- word [REQUIRED]: The word you are defining. Check [this URL](https://zealous-flower-0f27b070f.2.azurestaticapps.net/) for all words we currently have.
- content [REQUIRED]: The definition. No more than 3 sentences.
- learn more URL [REQUIRED]: Page where people can visit to learn more about the word.
- tag [REQUIRED, select one]: Tech category the word fits in. Options: compute, security, service, general, analytics, developer tools, web, networking, database, storage, devops, ai/ml, identiy, iot, monitoring.
- abbreviation [OPTIONAL]: If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.
- author name [REQUIRED]: Your name.
- author link [REQUIRED]: The URL you want your name to link to.

{
  "word": "Landing Zone",
  "content": "A cloud service that enables organizations to automate the creation of new cloud environments/accounts with their permitted services, custom applications, policies and permissions. This way the organization is able to package a custom cloud environment as a product deployed on-demand with all the necessary resources for their specific use case and operation.",
  "learn_more_URL":"https://docs.aws.amazon.com/prescriptive-guidance/latest/strategy-migration/aws-landing-zone.html",
  "tag":"service",
  "abbreviation": "LZ",
  "author_name":"Foluso Ogunsakin",
  "author_link": "https://twitter.com/folusomaine"
}

**Comment by madebygps** [comment]
Added! thank you so much.
