### ISSUE TITLE
Submit a Cloud Definition - IaC

### ISSUE THREAD

**Issue by rishabkumar7** [learntocloud/cloud-dictionary#41]
Fill out the JSON below with the following.

- word [REQUIRED]: Infrastructure as Code
- content [REQUIRED]: IAC is a DevOps practise that aims to manage and provision infrastructure through code and automated processes rather than manual procedures. Goal is to provide version control, repeatability, and reliability in infrastructure management.
- learn more URL [REQUIRED]: https://www.redhat.com/en/topics/automation/what-is-infrastructure-as-code-iac
- tag [REQUIRED, select one]: devops
- abbreviation [OPTIONAL]: IaC
- author name [REQUIRED]: Rishab Kumar
- author link [REQUIRED]: https://twitter.com/rishabk7

{
  "word": "Infrastructure as Code",
  "content": "IAC is a DevOps practise that aims to manage and provision infrastructure through code and automated processes rather than manual procedures. Goal is to provide version control, repeatability, and reliability in infrastructure management.",
  "learn_more_URL":"https://www.redhat.com/en/topics/automation/what-is-infrastructure-as-code-iac",
  "tag":"devops",
  "abbreviation": "IaC",
  "author_name":"Rishab Kumar",
  "author_link": "https://twitter.com/rishabk7"
}

**Comment by madebygps** [comment]
nice

**Comment by madebygps** [comment]
added
