### ISSUE TITLE
Submit a Cloud Definition - disaster recovery

### ISSUE THREAD

**Issue by jgarrels** [learntocloud/cloud-dictionary#42]
Fill out the JSON below with the following.

- word [REQUIRED]: The word you are defining. Check [this URL](https://zealous-flower-0f27b070f.2.azurestaticapps.net/) for all words we currently have.
- content [REQUIRED]: The definition. No more than 3 sentences.
- learn more URL [REQUIRED]: Page where people can visit to learn more about the word.
- tag [REQUIRED, select one]: Tech category the word fits in. Options: compute, security, service, general, analytics, developer tools, web, networking, database, storage, devops, ai/ml, identiy, iot, monitoring.
- abbreviation [OPTIONAL]: If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.
- author name [REQUIRED]: Your name.
- author link [REQUIRED]: The URL you want your name to link to.

{
  "word": "disaster recovery",
  "content": "The process through which a company addresses outages and disasters to ensure business and application continuity. Key components include a timeline for recovery, backups, anticipating possible problems and addressing single points of failure.",
  "learn_more_URL":"https://aws.amazon.com/what-is/disaster-recovery/",
  "tag":"general",
  "abbreviation": "",
  "author_name":"Jonathan Garrels",
  "author_link": "https://www.linkedin.com/in/jonathan-garrels/"
}

**Comment by mehrdadbn9** [comment]
hi i like to contribute but you've write all json file what can i do?

**Comment by madebygps** [comment]
Great one, thank you for submitted, I've added it :)
