### ISSUE TITLE
Submit a Cloud Definition: Utility Computing 

### ISSUE THREAD

**Issue by EmpGit** [learntocloud/cloud-dictionary#43]
Fill out the JSON below with the following.

- word [REQUIRED]: Utility Computing

- content [REQUIRED]: Utility Computing is a service provisioning model where a provider makes computing resources, infrastructure management and technical services available to customers as they need them.

- learn more URL [REQUIRED]: https://www.techtarget.com/searchdatacenter/definition/utility-computing

- tag [REQUIRED, select one]: General
- abbreviation [OPTIONAL]: 
- author name [REQUIRED]: Tyrik Emptage 
- author link [REQUIRED]: https://www.linkedin.com/in/tyrik-emptage

{
  "word": "Utility Computing"
  "content": "Utility computing is a service provisioning model where a provider makes computing resources, infrastructure management and technical services available to customers as they need them."
  "learn_more_URL":" https://www.techtarget.com/searchdatacenter/definition/utility-computing",
  "tag":"General",
  "abbreviation": " ",
  "author_name":"Tyrik Emptage",
  "author_link": "https://www.linkedin.com/in/tyrik-emptage'
}

**Comment by madebygps** [comment]
Hi @EmpGit I checked your definition with the learn more URL you provided, and it looks like a copy/paste. I recommended you read more about the concept and then submit your own original definition.

Thank you.

**Comment by EmpGit** [comment]
Thanks for letting me know, @madebygps. I was curious about what I should put. I will look into this further and update with my definition.

-Tyrik Emptage
