### ISSUE TITLE
Recovery Point Objective (RPO)

### ISSUE THREAD

**Issue by davidmosaku** [learntocloud/cloud-dictionary#45]
Fill out the JSON below with the following.

- word [REQUIRED]: The word you are defining. Check [this URL](https://zealous-flower-0f27b070f.2.azurestaticapps.net/) for all words we currently have.
- content [REQUIRED]: The definition. No more than 3 sentences.
- learn more URL [REQUIRED]: Page where people can visit to learn more about the word.
- tag [REQUIRED, select one]: Tech category the word fits in. Options: compute, security, service, general, analytics, developer tools, web, networking, database, storage, devops, ai/ml, identiy, iot, monitoring.
- abbreviation [OPTIONAL]: If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.
- author name [REQUIRED]: Your name.
- author link [REQUIRED]: The URL you want your name to link to.

{
  "Recovery Point Objective": "",
  "RPO is your goal for the maximum amount of data the organization can tolerate losing. This parameter is measured in time: from the moment a failure occurs to your last valid data backup. For example, if you experience a failure now and your last full data backup was 24 hours ago, the RPO is 24 hours": "",
  "https://www.rubrik.com/insights/rto-rpo-whats-the-difference":"",
  "Disaster Recovery":"",
  "RPO": "",
  "David Mosaku":"",
  "https://www.linkedin.com/in/davidmosaku/": ""
}

**Comment by madebygps** [comment]
Hi @davidmosaku I checked your definition with the learn more URL you provided and it looks like a copy/paste. I recommended you read more about the concept and then submit your own original definition.

Thank you.
