### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by TerminalsandCoffee** [learntocloud/cloud-dictionary#47]
Fill out the JSON below with the following.

- word [REQUIRED]: The word you are defining. Check [this URL](https://zealous-flower-0f27b070f.2.azurestaticapps.net/) for all words we currently have.
- content [REQUIRED]: The definition. No more than 3 sentences.
- learn more URL [REQUIRED]: Page where people can visit to learn more about the word.
- tag [REQUIRED, select one]: Tech category the word fits in. Options: compute, security, service, general, analytics, developer tools, web, networking, database, storage, devops, ai/ml, identiy, iot, monitoring.
- abbreviation [OPTIONAL]: If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.
- author name [REQUIRED]: Your name.
- author link [REQUIRED]: The URL you want your name to link to.

{
  "word": Amazon Elastic Compute Cloud"",
  "content": Amazon Elastic Compute Cloud provides scalable computing capacity in the AWS Cloud. We are able to create and run virtual machines in the cloud, we call these virtual machines,'instances'"",
  "learn_more_URL": https://docs.aws.amazon.com/ec2/?icmpid=docs_homepage_featuredsvcs"",
  "tag": compute"",
  "abbreviation": AWS EC2"",
  "author_name": Rafael Martinez"",
  "author_link": https://rafaelmartinez.cloud/""
}

**Comment by madebygps** [comment]
Contributes to open source ✅

thank you :)
