### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by schamiir** [learntocloud/cloud-dictionary#5]
- Word [REQUIRED]: Cloud Service Provider
- Content [REQUIRED]: a company that offers cloud computing services to its customers, including infrastructure as a service (IaaS), platform as a service (PaaS), and software as a service (SaaS). These services are delivered over the internet and are typically provided on a subscription basis, allowing customers to pay only for the resources they consume. 
- Author Name [REQUIRED]: Schamir 'ZONA' Poliard
- Author Link [REQUIRED]: https://twitter.com/SupernovaZona
- Learn More URL [REQUIRED]: https://www.techtarget.com/searchitchannel/definition/cloud-service-provider-cloud-provider
- Category [REQUIRED, select one]: Service
- Abbreviation [OPTIONAL]: CSP

**Comment by madebygps** [comment]
love it, adding it now, thank you :)

![image](https://user-images.githubusercontent.com/6733686/217544715-5d69a48c-4802-4483-9e5c-e987241380a7.png)

**Comment by schamiir** [comment]
Awesome! Thank you so much! 🤗
