### ISSUE TITLE
Submit a Cloud Definition - Content Delivery Network

### ISSUE THREAD

**Issue by Harshith-Shetty** [learntocloud/cloud-dictionary#51]
{
  "word": "Content Delivery Network",
  "content": "A Content Delivery Network (CDN) is a large distributed system of servers that are deployed in multiple data centres across the Internet. The main goal of a CDN is to provide fast and reliable delivery of web content to users located at different locations around the world. CDNs use a variety of techniques to cache and distribute content, such as HTTP caching, server-side caching, and client-side caching, to ensure that content is delivered quickly and efficiently to end users.",
  "learn_more_URL":"https://www.cloudflare.com/learning/cdn/what-is-a-cdn/",
  "tag": "web",
  "abbreviation": "CDN",
  "author_name": "Harshith Shetty",
  "author_link": "https://github.com/Harshith-Shetty"
}

**Comment by madebygps** [comment]
Added, thank you :)
