### ISSUE TITLE
Submit a Cloud Definition - Microservice

### ISSUE THREAD

**Issue by Harshith-Shetty** [learntocloud/cloud-dictionary#53]
{
  "word": "Microservice",
  "content": "A microservice is a software architectural style that structures an application as a collection of small, independent services that communicate with each other over a network. Each microservice has a specific function and can be developed, deployed, and scaled independently, allowing for greater flexibility and resilience in the overall system. The microservice architecture is commonly used to build complex, large-scale applications.",
  "learn_more_URL": "https://aws.amazon.com/microservices/",
  "tag": "developer tools",
  "author_name": "Harshith Shetty",
  "author_link": "https://github.com/Harshith-Shetty"
}

**Comment by madebygps** [comment]
Added, thank you!
