### ISSUE TITLE
Infrastructure as Code

### ISSUE THREAD

**Issue by SahilGupta2810** [learntocloud/cloud-dictionary#55]
Fill out the JSON below with the following.

- word [REQUIRED]: The word you are defining. Check [this URL](https://zealous-flower-0f27b070f.2.azurestaticapps.net/) for all words we currently have.
- content [REQUIRED]: The definition. No more than 3 sentences.
- learn more URL [REQUIRED]: Page where people can visit to learn more about the word.
- tag [REQUIRED, select one]: Tech category the word fits in. Options: compute, security, service, general, analytics, developer tools, web, networking, database, storage, devops, ai/ml, identiy, iot, monitoring.
- abbreviation [OPTIONAL]: If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.
- author name [REQUIRED]: Your name.
- author link [REQUIRED]: The URL you want your name to link to.

{
  "word": " IaC (Infrastructure as Code) ",
  "content": " Helps Developer Teams / Individuals leverage building and managing the Cloud Infrastructure through code instead of manual process. ",
  "learn_more_URL":" ",
  "tag":" developer tools ",
  "abbreviation": "",
  "author_name": " Sahil Gupta ",
  "author_link": " https://www.linkedin.com/in/sahilgupta2810/ "
}

**Comment by SahilGupta2810** [comment]
Thanks for this opportunity. Please review the submitted defination.

**Comment by SahilGupta2810** [comment]
{
"word": " IaC (Infrastructure as Code) ",
"content": " Helps Developer Teams / Individuals leverage building and managing the Cloud Infrastructure through code instead of manual process. ",
"learn_more_URL":"https://www.linkedin.com/posts/sahilgupta2810_cdk-101-activity-6946843753068249088-rIa0?utm_source=share&utm_medium=member_desktop",
"tag":" developer tools ",
"abbreviation": "",
"author_name": " Sahil Gupta ",
"author_link": " https://www.linkedin.com/in/sahilgupta2810/ "
}

**Comment by madebygps** [comment]
Thank you @SahilGupta2810. It looks like someone provided this word already. Please feel free to review the list of already submitted definitions and submit a new one. thank you.
