### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by harisdev-netizen** [learntocloud/cloud-dictionary#60]
Do NOT copy/paste a definition from somewhere else. Read about the word you want to define and come up with your own definition.

{
  "word": "Cloud Computing",
  "content": "A model for enabling convenient, on-demand network access to share pool of configurable computing resources that can be rapidly provisioned and released with minimal management effort or service provider interaction",
  "learn_more_URL":"https://learntocloud.guide",
  "tag":"cloud computing, AWS cloud computing, cloud storage, cloud network",
  "abbreviation": "",
  "author_name":"Haris",
  "author_link": "https://github.com/harisdev-netizen"
}

Fill out the JSON below with the following.

- word [REQUIRED]: The word you are defining. Check [this URL](https://zealous-flower-0f27b070f.2.azurestaticapps.net/) for all words we currently have.
- content [REQUIRED]: The definition. No more than 3 sentences.
- learn more URL [REQUIRED]: Page where people can visit to learn more about the word.
- tag [REQUIRED, select one]: Tech category the word fits in. Options: compute, security, service, general, analytics, developer tools, web, networking, database, storage, devops, ai/ml, identiy, iot, monitoring.
- abbreviation [OPTIONAL]: If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.
- author name [REQUIRED]: Your name.
- author link [REQUIRED]: The URL you want your name to link to.

**Comment by madebygps** [comment]
Added, thank you!
