### ISSUE TITLE
Submit a Cloud Definition - Docker

### ISSUE THREAD

**Issue by rishabkumar7** [learntocloud/cloud-dictionary#7]
- Word [REQUIRED]: **docker**
- Content [REQUIRED]: Docker is an open-source platform for automating application deployment, scaling, and management as containers. Containers are executable packages that include everything needed to run a piece of software, including the code, runtime, libraries, environment variables, and more.
- Author Name [REQUIRED]: Rishab Kumar
- Author Link [REQUIRED]: https://twitter.com/rishabk7
- Learn More URL [REQUIRED]: https://docs.docker.com/get-started/overview/
- Category [REQUIRED, select one]: devops
- Abbreviation [OPTIONAL]: If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

**Comment by madebygps** [comment]
Thank you! added.
