### ISSUE TITLE
Submit a Cloud Definition: Utility computing 

### ISSUE THREAD

**Issue by EmpGit** [learntocloud/cloud-dictionary#73]
Do NOT copy/paste a definition from somewhere else. Read about the word you want to define and come up with your own definition. Copy/Paste submissions will be closed and not added.

Fill out the JSON with your submission:

```json
    {
    "word": "Utility Computing",
    "content": "A valuable supplier capable of providing access to cost effective computing resources for the benefit of a given company or organization.",
    "learn_more_URL":"https://www.givainc.com/blog/index.cfm/2021/11/2/grid-computing-vs-cluster-computing-vs-utility-computing-vs-cloud-computing-advantages-disadvantages",
    "tag":"General",
    "abbreviation": "",
    "author_name":"Tyrik Emptage",
    "author_link": "https://www.linkedin.com/in/tyrik-emptage"
    }
```
Fill out the JSON below with the following.

### Word (REQUIRED)
Utility Computing

#### Content (REQUIRED)
A valuable supplier capable of providing access to cost effective computing resources for the benefit of a given company or organization

### learn more URL (REQUIRED)
https://www.givainc.com/blog/index.cfm/2021/11/2/grid-computing-vs-cluster-computing-vs-utility-computing-vs-cloud-computing-advantages-disadvantages

### tag (REQUIRED and select one)
- general

### abbreviation (OPTIONAL)

If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

### author name (REQUIRED)
Tyrik Emptage 

### author link (REQUIRED)
https://www.linkedin.com/in/tyrik-emptage

**Comment by madebygps** [comment]
Added, thank you.
