### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by davWK** [learntocloud/cloud-dictionary#74]
Do NOT copy/paste a definition from somewhere else. Read about the word you want to define and come up with your own definition. Copy/Paste submissions will be closed and not added.

Fill out the JSON with your submission:

```json
    {
    "word": "Canary release",
    "content": "A canary release is a deployment strategy used in software development, in which a new version of an application is released to a small group of users before it is made available to the wider user base
",
    "learn_more_URL":"https://cloud.google.com/blog/products/gcp/how-release-canaries-can-save-your-bacon-cre-life-lessons",
    "tag":"devops",
    "abbreviation": "",
    "author_name":"David K. WOGLO",
    "author_link": "https://www.linkedin.com/in/kodjovi-david-woglo"
    }
```
Fill out the JSON below with the following.

### Word (REQUIRED)

The word you are defining. Check [this URL](https://zealous-flower-0f27b070f.2.azurestaticapps.net/) for all words we currently have.

#### Content (REQUIRED)

The definition. No more than 3 sentences.

### learn more URL (REQUIRED)

Website where people can visit to learn more about the word.

### tag (REQUIRED and select one)

Tech category the word fits in. Options:

- compute
- security
- service
- general
- analytics
- developer tool
- web
- networking
- database
- storage
- devops
- ai/ml
- identity
- iot
- monitoring
- cost management
- disaster recovery

### abbreviation (OPTIONAL)

If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

### author name (REQUIRED)

Your name.

### author link (REQUIRED)

The URL you want your name to link to.

**Comment by madebygps** [comment]
Hi there, the definition you provided is more an example of canary release instead of definition. Could you give it another try please.

**Comment by davWK** [comment]
yes sure !

**Comment by davWK** [comment]
Do NOT copy/paste a definition from somewhere else. Read about the word you want to define and come up with your own definition. Copy/Paste submissions will be closed and not added.

Fill out the JSON with your submission:

```json
    {
    "word": "Canary release",
    "content": "A canary release is a deployment strategy used in software development, in which a new version of an application is released to a small group of users before it is made available to the wider user base
",
    "learn_more_URL":"https://cloud.google.com/blog/products/gcp/how-release-canaries-can-save-your-bacon-cre-life-lessons",
    "tag":"devops",
    "abbreviation": "",
    "author_name":"David K. WOGLO",
    "author_link": "https://www.linkedin.com/in/kodjovi-david-woglo"
    }
```
Fill out the JSON below with the following.

### Word (REQUIRED)

The word you are defining. Check [this URL](https://zealous-flower-0f27b070f.2.azurestaticapps.net/) for all words we currently have.

#### Content (REQUIRED)

The definition. No more than 3 sentences.

### learn more URL (REQUIRED)

Website where people can visit to learn more about the word.

### tag (REQUIRED and select one)

Tech category the word fits in. Options:

- compute
- security
- service
- general
- analytics
- developer tool
- web
- networking
- database
- storage
- devops
- ai/ml
- identity
- iot
- monitoring
- cost management
- disaster recovery

### abbreviation (OPTIONAL)

If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

### author name (REQUIRED)

Your name.

### author link (REQUIRED)

The URL you want your name to link to.

**Comment by madebygps** [comment]
Great job! Thank you, I've added this.
