### ISSUE TITLE
Submit a Cloud Definition for Kubernetes

### ISSUE THREAD

**Issue by ahmedk2** [learntocloud/cloud-dictionary#8]
- Word [REQUIRED]: Kubernetes
- Content [REQUIRED]: Kubernetes, or K8s for short, is an open-source container-orchestration tool designed by Google. It's used for bundling and managing clusters of containerized applications — a process known as 'orchestration' .
- Author Name [REQUIRED]: Khalid Ahmed
- Author Link [REQUIRED]: https://github.com/ahmedk2
- Learn More URL [REQUIRED]: https://kubernetes.io/
- Category [REQUIRED, select one]: compute, devops,
- Abbreviation [OPTIONAL]:  K8s, K8

**Comment by ahmedk2** [comment]
I edited this to be Kubernetes since Rishab took Docker

**Comment by rishabkumar7** [comment]
i am sorry @ahmedk2 just few minutes early!

**Comment by madebygps** [comment]
Added, thank you very much!
