### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by clayhickman** [learntocloud/cloud-dictionary#80]
Do NOT copy/paste a definition from somewhere else. Read about the word you want to define and come up with your own definition. Copy/Paste submissions will be closed and not added.

Fill out the JSON with your submission:

```json
    {
    "word": "Internet Protocol",
    "content": "The Internet Protocol is a Layer 3 network communications protocol which adds cross network addressing and routing capabilities to move data (encapsulated in datagrams) across Layer 2 networks from source host to destination host without direct links",
"learn_more_URL":"https://en.m.wikipedia.org/wiki/Internet_Protocol",
    "tag":"networking",
    "abbreviation": "IP",
    "author_name":"Clay Hickman",
    "author_link": "https://github.com/clayhickman"
    }
```
Fill out the JSON below with the following.

### Word (REQUIRED)

The word you are defining. Check [this URL](https://zealous-flower-0f27b070f.2.azurestaticapps.net/) for all words we currently have.

#### Content (REQUIRED)

The definition. No more than 3 sentences.

### learn more URL (REQUIRED)

Website where people can visit to learn more about the word.

### tag (REQUIRED and select one)

Tech category the word fits in. Options:

- compute
- security
- service
- general
- analytics
- developer tool
- web
- networking
- database
- storage
- devops
- ai/ml
- identity
- iot
- monitoring
- cost management
- disaster recovery

### abbreviation (OPTIONAL)

If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

### author name (REQUIRED)

Your name.

### author link (REQUIRED)

The URL you want your name to link to.

**Comment by madebygps** [comment]
Thank you, added :)
