### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by AdeZwart** [learntocloud/cloud-dictionary#81]
Do NOT copy/paste a definition from somewhere else. Read about the word you want to define and come up with your own definition. Copy/Paste submissions will be closed and not added.

Fill out the JSON with your submission:

```json
    {
    "word": "Pipeline",
    "content": "A pipeline is a set of automated steps to build, test and deploy your code. This could be infrastructure and/or application code. Pipelines are used to implement CI/CD.",
    "learn_more_URL":"https://www.youtube.com/watch?v=nLRHV2sRTe8",
    "tag":"devops",
    "abbreviation": "",
    "author_name":"André de Zwart",
    "author_link": "https://github.com/adezwart"
    }
```
Fill out the JSON below with the following.

### Word (REQUIRED)

The word you are defining. Check [this URL](https://zealous-flower-0f27b070f.2.azurestaticapps.net/) for all words we currently have.

#### Content (REQUIRED)

The definition. No more than 3 sentences.

### learn more URL (REQUIRED)

Website where people can visit to learn more about the word.

### tag (REQUIRED and select one)

Tech category the word fits in. Options:

- compute
- security
- service
- general
- analytics
- developer tool
- web
- networking
- database
- storage
- devops
- ai/ml
- identity
- iot
- monitoring
- cost management
- disaster recovery

### abbreviation (OPTIONAL)

If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

### author name (REQUIRED)

Your name.

### author link (REQUIRED)

The URL you want your name to link to.

**Comment by madebygps** [comment]
Good one, added, thank you.
