### ISSUE TITLE
Submit a Cloud Definition

### ISSUE THREAD

**Issue by crivas01** [learntocloud/cloud-dictionary#89]
Do NOT copy/paste a definition from somewhere else. Read about the word you want to define and come up with your own definition. Copy/Paste submissions will be closed and not added.

Fill out the JSON with your submission:

```json
    {
    "word": "Media Access Control Address",
    "content": "A 12-digit unique identifier embedded on every computer or network interface card that can connect to the internet. The MAC address is used to identify devices on the network and ensures data is sent to the correct device.",
    "learn_more_URL":"https://www.howtogeek.com/764868/what-is-a-mac-address-and-how-does-it-work/",
    "tag":"networking",
    "abbreviation": "MAC Address",
    "author_name":"Chris Rivas",
    "author_link": "https://www.linkedin.com/in/chris-rivas4/"
    }
```
Fill out the JSON below with the following.

### Word (REQUIRED)

The word you are defining. Check [this URL](https://zealous-flower-0f27b070f.2.azurestaticapps.net/) for all words we currently have.

#### Content (REQUIRED)

The definition. No more than 3 sentences.

### learn more URL (REQUIRED)

Website where people can visit to learn more about the word.

### tag (REQUIRED and select one)

Tech category the word fits in. Options:

- compute
- security
- service
- general
- analytics
- developer tool
- web
- networking
- database
- storage
- devops
- ai/ml
- identity
- iot
- monitoring
- cost management
- disaster recovery

### abbreviation (OPTIONAL)

If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

### author name (REQUIRED)

Your name.

### author link (REQUIRED)

The URL you want your name to link to.

**Comment by madebygps** [comment]
I've added this, thank you.
