### ISSUE TITLE
Cloud definition 

### ISSUE THREAD

**Issue by rghdrizzle** [learntocloud/cloud-dictionary#9]
- Word [REQUIRED]: vendor lockin
- Content [REQUIRED]: Vendor lock-in refers to a situation where the cost of switching to a different vendor is so high that the customer is essentially stuck with the original vendor. Because of financial pressures, an insufficient workforce, or the need to avoid interruptions to business operations, the customer is "locked in" to what may be an inferior product or service.
- Author Name [REQUIRED]: Luqmaan Hakeem
- Author Link [REQUIRED]: [The URL you want your name to link to.](https://github.com/rghdrizzle)
- Learn More URL [REQUIRED]: [Page where people can visit to learn more about the word.](https://www.cloudflare.com/learning/cloud/what-is-vendor-lock-in/)
- Category [REQUIRED, select one]: general, service , cloud

**Comment by madebygps** [comment]
thank you! added :)
