### ISSUE TITLE
Secure Shell Protocol (SSH)

### ISSUE THREAD

**Issue by sandeep-tripathi** [learntocloud/cloud-dictionary#91]
Do NOT copy/paste a definition from somewhere else. Read about the word you want to define and come up with your own definition. Copy/Paste submissions will be closed and not added.

Fill out the JSON with your submission:

```json
    {
    "word": "Secure Shell Protocol  ",
    "content": "A cryptography based network protocol to establish connection with a server-client architecture to access a remote computer along with user authentication.",
    "learn_more_URL":"https://en.wikipedia.org/wiki/Secure_Shell",
    "tag":"Linux",
    "abbreviation": "SSH",
    "author_name":"Sandeep Tripathi",
    "author_link": "https://www.linkedin.com/in/sandeep-tripathi-a7088a71/"
    }
```
Fill out the JSON below with the following.

### Word (REQUIRED)

The word you are defining. Check [this URL](https://zealous-flower-0f27b070f.2.azurestaticapps.net/) for all words we currently have.

#### Content (REQUIRED)

The definition. No more than 3 sentences.

### learn more URL (REQUIRED)

Website where people can visit to learn more about the word.

### tag (REQUIRED and select one)

Tech category the word fits in. Options:

- compute
- security
- service
- general
- analytics
- developer tool
- web
- networking
- database
- storage
- devops
- ai/ml
- identity
- iot
- monitoring
- cost management
- disaster recovery

### abbreviation (OPTIONAL)

If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

### author name (REQUIRED)

Your name.

### author link (REQUIRED)

The URL you want your name to link to.

**Comment by madebygps** [comment]
Added, thank you :)
