### ISSUE TITLE
Submit a Cloud Definition: Continuous Integration

### ISSUE THREAD

**Issue by joeterlecki** [learntocloud/cloud-dictionary#97]
Do NOT copy/paste a definition from somewhere else. Read about the word you want to define and come up with your own definition. Copy/Paste submissions will be closed and not added.

Fill out the JSON with your submission:

```json
    {
    "word": "Continuous Integration",
    "content": "The practice of committing and merging all development and feature code to a main git branch numerous times daily. All commits and merges trigger automated builds and tests to ensure quality and security are maintained.  Continuous Integration's main goal is to address potential bugs and produce a consumable artifact such as a working Docker container. ",
    "learn_more_URL":"https://www.harness.io/blog/what-is-continuous-integration",
    "tag":"devops",
    "abbreviation": "CI",
    "author_name":"Joe Terlecki",
    "author_link": "https://www.youtube.com/c/JoeTerlecki"
    }
```
Fill out the JSON below with the following.

### Word (REQUIRED)

The word you are defining. Check [this URL](https://zealous-flower-0f27b070f.2.azurestaticapps.net/) for all words we currently have.

#### Content (REQUIRED)

The definition. No more than 3 sentences.

### learn more URL (REQUIRED)

Website where people can visit to learn more about the word.

### tag (REQUIRED and select one)

Tech category the word fits in. Options:

- compute
- security
- service
- general
- analytics
- developer tool
- web
- networking
- database
- storage
- devops
- ai/ml
- identity
- iot
- monitoring
- cost management
- disaster recovery

### abbreviation (OPTIONAL)

If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

### author name (REQUIRED)

Your name.

### author link (REQUIRED)

The URL you want your name to link to.

**Comment by madebygps** [comment]
Added, thank you again.
