### ISSUE TITLE
Submit a Cloud Definition : Azure Functions

### ISSUE THREAD

**Issue by clearfountain** [learntocloud/cloud-dictionary#99]
Do NOT copy/paste a definition from somewhere else. Read about the word you want to define and come up with your own definition. Copy/Paste submissions will be closed and not added.

Fill out the JSON with your submission:

```json
    {
    "word": "Azure Functions",
    "content": "Azure Functions is an Azure feature for building a serverless application whose code is executed only when a chosen event is triggered. It is serverless because servers do not have to be configured or managed. Since the resources are assigned when an event occurs, this can be cost-effective for applications that handle short tasks.",
    "learn_more_URL":"https://learn.microsoft.com/en-us/azure/azure-functions/",
    "tag":"compute",
    "abbreviation": "func",
    "author_name":"John Edet",
    "author_link": "https://github.com/clearfountain"
    }
```
Fill out the JSON below with the following.

### Word (REQUIRED)

The word you are defining. Check [this URL](https://zealous-flower-0f27b070f.2.azurestaticapps.net/) for all words we currently have.

#### Content (REQUIRED)

The definition. No more than 3 sentences.

### learn more URL (REQUIRED)

Website where people can visit to learn more about the word.

### tag (REQUIRED and select one)

Tech category the word fits in. Options:

- compute
- security
- service
- general
- analytics
- developer tool
- web
- networking
- database
- storage
- devops
- ai/ml
- identity
- iot
- monitoring
- cost management
- disaster recovery

### abbreviation (OPTIONAL)

If the word is commonly abbreviated, please provide it. For example, command line interface is often abbreviated as CLI.

### author name (REQUIRED)

Your name.

### author link (REQUIRED)

The URL you want your name to link to.

**Comment by madebygps** [comment]
Added, thank you :)
